name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: vighasks/todolist-docker-app:v1.0

      - name: Build and push MySQL image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: vighasks/todolist-mysql:v1.0

      - name: Read Release Notes into Environment Variable
        id: read_release_notes
        run: echo "RELEASE_NOTES=$(cat release-notes.md)" >> $GITHUB_ENV

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker network create --driver bridge image-network || true

            docker pull vighasks/todolist-docker-app:v1.0
            docker stop todolist-docker-app || true
            docker rm todolist-docker-app || true
            docker run --privileged -d --name todolist-docker-app -p 8081:4000 \
              --network image-network \
              vighasks/todolist-docker-app:v1.0

            docker pull vighasks/todolist-mysql:v1.0
            docker stop todolist-docker-mysql || true
            docker rm todolist-docker-mysql || true
            docker run -d --name todolist-docker-mysql --network image-network \
              -e MYSQL_ROOT_PASSWORD=root_password \
              -p 3306:3306 vighasks/todolist-mysql:v1.0

            docker exec todolist-docker-app npx prisma migrate deploy
            docker system prune -f --volumes
